#!/usr/bin/env python3
"""
Writes and reads module-scoped CLAUDE.md / GEMINI.md / AGENTS.md context files.
Called at the end of each CommandingSystem command (and by the dynamic
context-handoff hook in plugin/context_guard.py) to persist episodic memory.

Canonical copy lives at plugin/skills/CommandingSystem/auto_test/; this is the
same contract documented in CommandingSystem/context_handoff_workflow.md.

Usage:
    python3 context_writer.py write --module vpcs_hr --version 19 \
        --command plan-analysis --summary "HR extension for employee..." \
        --models "vpcs.hr.employee,vpcs.hr.leave" \
        --tasks-done 0 --tasks-total 6 \
        --module-dir /path/to/vpcs_hr

    python3 context_writer.py read --module-dir /path/to/vpcs_hr
"""

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

CONTEXT_FILENAME = "CLAUDE.md"
SESSION_FILENAME = "sessions/context_handoff.json"


def write_context(
    module_dir: Path,
    module_name: str,
    version: str,
    command: str,
    summary: str,
    models: list,
    tasks_done: int,
    tasks_total: int,
    extra=None,
):
    session_data = _load_session(module_dir)

    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    session_data["module"] = module_name
    session_data["version"] = version
    session_data["last_command"] = command
    session_data["last_updated"] = now_iso
    session_data["models"] = models or session_data.get("models", [])
    session_data["tasks_done"] = tasks_done
    session_data["tasks_total"] = tasks_total
    if extra:
        session_data.setdefault("extra", {}).update(extra)

    history = session_data.setdefault("command_history", [])
    history.append({
        "command": command,
        "timestamp": now_iso,
        "summary": summary,
        "tasks_done": tasks_done,
        "tasks_total": tasks_total,
    })

    _save_session(module_dir, session_data)

    claude_md = _build_claude_md(session_data, summary)
    (module_dir / CONTEXT_FILENAME).write_text(claude_md, encoding="utf-8")
    (module_dir / "GEMINI.md").write_text(claude_md, encoding="utf-8")
    (module_dir / "AGENTS.md").write_text(claude_md, encoding="utf-8")

    print(f"Context written: {module_dir / CONTEXT_FILENAME}")
    print(f"Context written: {module_dir / 'GEMINI.md'}")
    print(f"Context written: {module_dir / 'AGENTS.md'}")


def read_context(module_dir: Path) -> dict:
    path = module_dir / CONTEXT_FILENAME
    if not path.exists():
        return {}
    return _load_session(module_dir)


def _build_claude_md(session: dict, latest_summary: str) -> str:
    module = session.get("module", "unknown")
    version = session.get("version", "?")
    last_cmd = session.get("last_command", "?")
    tasks_done = session.get("tasks_done", 0)
    tasks_total = session.get("tasks_total", 0)
    models = session.get("models", [])
    last_updated = session.get("last_updated", "?")
    history = session.get("command_history", [])

    lines = [
        f"# {module} — Odoo {version} Development Context",
        "",
        "> Auto-generated by CommandingSystem. Do not edit manually.",
        f"> Last updated: {last_updated} by `/{last_cmd}`",
        "",
        "## Current State",
        "",
        f"- **Module**: `{module}`",
        f"- **Odoo Version**: {version}",
        f"- **Last command**: `/{last_cmd}`",
        f"- **Tasks**: {tasks_done}/{tasks_total} complete",
        "",
    ]

    if tasks_total > 0:
        pct = int(tasks_done / tasks_total * 100)
        bar = "█" * (pct // 10) + "░" * (10 - pct // 10)
        lines += [f"  Progress: [{bar}] {pct}%", ""]

    if models:
        lines += ["## Custom Models", ""]
        for m in models:
            lines.append(f"- `{m}`")
        lines.append("")

    lines += [
        "## Latest Summary",
        "",
        latest_summary,
        "",
    ]

    if history:
        lines += ["## Command History", ""]
        for h in reversed(history[-5:]):
            ts = h.get("timestamp", "")[:10]
            lines.append(f"- `/{h['command']}` ({ts}): {h['summary'][:100]}")
        lines.append("")

    lines += [
        "## Agent Instructions",
        "",
        f"- Load `Odoo{version}CodingStandard/SKILL.md` before any coding",
        f"- Load `OdooTools{version}/SKILL.md` for utility functions",
        "- Module docs: see `docs/requirements.md`, `docs/design.md`, `docs/tasks.md`",
        "- Auto-tests: run `CommandingSystem/auto_test/auto_test_runner.py` after each task",
        "- Context update: run `CommandingSystem/auto_test/context_writer.py write` after each command",
        "",
    ]

    extra = session.get("extra", {})
    if extra.get("tech_decisions"):
        lines += ["## Technical Decisions", ""]
        for k, v in extra["tech_decisions"].items():
            lines.append(f"- **{k}**: {v}")
        lines.append("")

    if extra.get("context_handoff"):
        ch = extra["context_handoff"]
        lines += [
            "## ⚠️ Dynamic Context Handoff",
            "",
            f"- Triggered at **{ch.get('usage_pct', '?')}%** context usage "
            f"(threshold: {ch.get('threshold_pct', '?')}%)",
            f"- Triggered by: `{ch.get('triggered_by', 'unknown')}`",
            f"- Triggered at: {ch.get('triggered_at', '?')}",
            "- A fresh agent session should resume purely from this file plus "
            "`docs/tasks.md` — do not re-derive already-completed work.",
            "",
        ]

    return "\n".join(lines)


def _load_session(module_dir: Path) -> dict:
    session_path = module_dir / SESSION_FILENAME
    if session_path.exists():
        return json.loads(session_path.read_text())
    return {}


def _save_session(module_dir: Path, data: dict):
    session_path = module_dir / SESSION_FILENAME
    session_path.parent.mkdir(parents=True, exist_ok=True)
    session_path.write_text(json.dumps(data, indent=2))


def main():
    parser = argparse.ArgumentParser(description="Context handoff writer/reader")
    sub = parser.add_subparsers(dest="action", required=True)

    w = sub.add_parser("write")
    w.add_argument("--module", required=True)
    w.add_argument("--module-dir", required=True)
    w.add_argument("--version", required=True)
    w.add_argument("--command", required=True)
    w.add_argument("--summary", required=True)
    w.add_argument("--models", default="")
    w.add_argument("--tasks-done", type=int, default=0)
    w.add_argument("--tasks-total", type=int, default=0)

    r = sub.add_parser("read")
    r.add_argument("--module-dir", required=True)

    args = parser.parse_args()
    module_dir = Path(args.module_dir)

    if args.action == "write":
        models = [m.strip() for m in args.models.split(",") if m.strip()]
        write_context(
            module_dir=module_dir,
            module_name=args.module,
            version=args.version,
            command=args.command,
            summary=args.summary,
            models=models,
            tasks_done=args.tasks_done,
            tasks_total=args.tasks_total,
        )
    elif args.action == "read":
        ctx = read_context(module_dir)
        print(json.dumps(ctx, indent=2))


if __name__ == "__main__":
    main()
